FROM python:3.13.3-slim-bookworm

RUN apt-get update && apt-get install -y libsass-dev build-essential git

# Example: Install 3rd party plugin dependencies
# RUN apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant
